### ISSUE TITLE
HTTP Client 2 does not need http:send

### ISSUE THREAD

**Issue by adamretter** [expath/expath-cg#77]
I am not certain that there is any point to having `http:send` in EXPath HTTP Client 2.0.

It is not backwards compatible with 1.0, and therefore not a simple upgrade path. It also introduces another function definition which we need to maintain without any gain.

An implementation is free of course to provide http-send from EXPath HTTP Client 1.0 alongside EXPath HTTP Client 2.0 functions.

Any arguments for keeping the new `http:send` function definition in EXPath HTTP Client 2.0?

**Comment by ChristianGruen** [comment]
Hi Adam, I would love to keep `http:send` in the specification. Otherwise, the legacy `http:send-request` function would need to be used to send more exotic HTTP methods (as e.g. used by WebDAV). Apart from that, I remember we had code in which the HTTP method is passed on as dynamic argument.

Or would you try to somehow merge the new `http:send` functionality into the existing `http:send-request` function?

**Comment by ChristianGruen** [comment]
…maybe the misunderstanding is that version 1.0 has `http:send-request`, while we would now add `http:send`?

**Comment by adamretter** [comment]
Ahhh! WebDav, that is indeed a good use-case for a function which allows the HTTP method to be generally specified!

So let's keep `http:send`.

HTTP 1.0 only supports the methods GET, HEAD, and PUT. So I think any methods outside of that are only supportable by HTTP 1.1, which allows [`extension-method`](https://tools.ietf.org/html/rfc2616#page-36). I think we will need to code that into the behaviour of the spec for `http:send`, so that if `"http-version": "1.0"` is specified in `$options` and we are given a non-HTTP 1.0 method, we should raise the error `http:version-error` (or whatever the error will be named).
