### ISSUE TITLE
Support for gzipped requests

### ISSUE THREAD

**Issue by ChristianGruen** [expath/expath-cg#82]
See discussion in https://github.com/expath/expath-cg/pull/78:

The current version of the specification provides a `content-encoding` option (which can be set to `gzip` and `deflate`:

* Maybe we can introduce a `gzip` option instead, which can be `true()` (for `gzip`) or `false()` (for `deflate`) instead?
* We should probably add some description on what happens exactly if the option is enabled.

**Comment by adamretter** [comment]
Personally I still prefer to have a `content-encoding` *option*, which can override a `content-encoding` *header*, rather than options for each possible value of content-encoding etc.

Some points to support my argument:

1. Options are often mutually exclusive, e.g. the content-encoding types of gzip and deflate.
    1. Setting `"gzip": true()` and `"deflate": true()` would cause confusion.  We would have to have a precedence rule, or an error.
    2. Setting `"gzip": false()` is in no way self-evident to the developer that defalte encoding will be used instead!
    3. Use of *options* `"content-encoding": "gzip"` or `"content-encoding": "deflate"` is much clearer. We just need to explicitly state that `options` are not the same as `headers`, and state what action, if any), the various options take to override headers.

2. We will end up with a profliferation of binary options, where a single enumerated option makes more sense.

3. We should "call a spade a spade" ;-)

**Comment by ChristianGruen** [comment]
Sounds all reasonable to me. And I could add that:

4. Your approach is more flexible if any other content encodings should be added to HTTP (or get more popular) in future.
